### ISSUE TITLE
Create Book relationships

### ISSUE THREAD

**Issue by Vimbayinashe** [fireblazrs/library-management-system#10]
- Book - Author @ManyToMany
- Book - BookType @onetomany
- Book - Genre - @onetomany
- ~~- Book - User @onetomany~~

**Comment by Vimbayinashe** [comment]
Book - Category has been removed.

**Comment by Vimbayinashe** [comment]
Book - User relationship has been moved to issue #56

**Comment by Vimbayinashe** [comment]
This would be nice to include in the project, however, if it is implemented please implement endpoints for Author, BookFormat & Genre.

**Comment by Ahsanadam** [comment]
Have we made all the necessary relations now ? What else do we need to do ?

**Comment by Ahsanadam** [comment]
I can see that BookEntity and AuthorEntity are not connected so that needs to be implemented.
