### ISSUE TITLE
Add Localhost 3307 in order to log in to mysql container.

### ISSUE THREAD

**Issue by Ahsanadam** [fireblazrs/library-management-system#24]

**Comment by Ahsanadam** [comment]
Om man lägger till 
ports:
  - "3307:3306"
så kan man logga in i mysql container på localhost:3307

**Comment by Ahsanadam** [comment]
What do we mean here? Where can we edit this configuration? Is it on the docker compose file ?

**Comment by Vimbayinashe** [comment]
> What do we mean here? Where can we edit this configuration? Is it on the docker compose file ?

Yes! The ports can be added under mysql service

```
ports:
    - "8080:8080"
```

**Comment by Ahsanadam** [comment]
Its done, you can review the pull request that I made and approve it.

**Comment by ToniKaru** [comment]
Closed by pull request #66
