### ISSUE TITLE
Create Remaining Book Endpoints

### ISSUE THREAD

**Issue by Vimbayinashe** [fireblazrs/library-management-system#59]
Create endpoints for BookEntity **excluding** the 3 endpoints below which have already been created in issue #58.

- ~~createBook~~
- ~~getAllBooks~~
- ~~getBookByISBN~~

**Comment by Ahsanadam** [comment]
We need to have a Bookcontroller and Bookrepository in order to do this or do you want me to create a BookRepository and BookController in order for it to work ?

**Comment by Vimbayinashe** [comment]
I w

> We need to have a Bookcontroller and Bookrepository in order to do this or do you want me to create a BookRepository and BookController in order for it to work ?

Yes, they are both required to create endpoints. You can either create a BookRepository & BookController which can later on be merged with those created in issue #51 or you can wait until that issue has been merged

**Comment by Ahsanadam** [comment]
Yes, I am going to create a BookRepository and a BookController in order for it to work.

**Comment by Ahsanadam** [comment]
I saw that you have already created a BookRepository and a BookController in a previous pull request , I will put in the deleteBook and findbyID method in BookService and BookController with suitable ENDPOINTS.
